# name: Hello World Workflow

# on:
#   push:
#     branches: [master]

# jobs: 
#   say_hello:
#     runs-on: ubuntu-22.04
#     steps:
#       - name: Print hello World
#         run: echo "Hello world !"



name: Deploy to Vercel

on:
  push:
    branches:
      - master
  
jobs:
  build_and_deploy:
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: npm install

      - name: build
        run: npm run build

      - name: Deploy to Vercel
        uses: amondnet/vercel-actions@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          alias-domain: domain.com
          working-directory: ./
          vercel-args: '--prod'